### ISSUE TITLE
Support draw image

### ISSUE THREAD

**Issue by normidar** [signmotion/pure_dart_ui#1]
Want to record the canvas like:

```dart
    final recorder = PictureRecorder();
    final canvas = Canvas(recorder,
        Rect.fromPoints(const Offset(0.0, 0.0), const Offset(200.0, 200.0)));
```

**Comment by syrokomskyi** [comment]
This package is not designed for that purpose, @normidar. 

But https://github.com/signmotion/flutter_image_converter I or You can expand with this wish.

**Comment by normidar** [comment]
> This package is not designed for that purpose, @normidar.
> 
> But https://github.com/signmotion/flutter_image_converter I or You can expand with this wish.

@signmotion 
But it seems not pure, I want to run it on command line.

**Comment by normidar** [comment]
Now I am using https://pub.dev/packages/image ,it is pure but image plugin is not easy to draw things.

**Comment by syrokomskyi** [comment]
This library is helper for substitute some useful Flutter dependencies, not CLI.

**Comment by normidar** [comment]
> This library is helper for substitute some useful Flutter dependencies, not CLI.

Got it, thank you ❤️ 

close this issue.
